### ISSUE TITLE
Puppetfile not found: incorrect error message

### ISSUE THREAD

**Issue by dplarson** [wfarr/henson#22]
If a `Pupeptfile` is not found, then `henson` will provide an error message. Except the error message is incorrect:

``` shell
# current message
/some/path/to/the/folder/Puppetfile does not exist, but it does not exist!

# what it probably should say
/some/path/to/the/folder/Puppetfile does not exist!
```

This incorrect/repeated message is caused by `lib/henson/friendly_errors.rb`, specifically line 12:

``` ruby
Henson.ui.error "#{e.message}, but it does not exist!"
```

Can anyone verify this mistake? If so I'll then make a pull request.

**Comment by aussielunix** [comment]
@dplarson this was fixed in wfarr/henson/pull/4
